### PR TITLE
feat(docs): added OpenSSF Scorecard Batch to increase clo-monitor score

### LINKED ISSUE #1353: Improve security clomonitor score
Current status
[CLOMonitor](https://clomonitor.io/projects/cncf/kubearmor)

```[tasklist]
### [KubeArmor](https://clomonitor.io/projects/cncf/kubearmor#kubearmor)
- [x] [Documentation - Roadmap](https://clomonitor.io/docs/topics/checks/#roadmap)  (thanks @rootxrishabh )
- [x] [License scanning](https://clomonitor.io/docs/topics/checks/#license-scanning)
- [x] [Artifact Hub badge](https://clomonitor.io/docs/topics/checks/#artifact-hub-badge)  (thanks @rootxrishabh )
- [x] [Community meeting](https://clomonitor.io/docs/topics/checks/#community-meeting)
- [x] [OpenSSF Scorecard badge](https://clomonitor.io/docs/topics/checks/#openssf-scorecard-badge)
- [ ] [Binary artifacts](https://clomonitor.io/docs/topics/checks/#binary-artifacts-from-openssf-scorecard)
- [ ] [Software bill of materials (SBOM)](https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom)
- [ ] [Signed releases](https://clomonitor.io/docs/topics/checks/#signed-releases-from-openssf-scorecard)
- [ ] [Token permissions](https://clomonitor.io/docs/topics/checks/#token-permissions-from-openssf-scorecard)
```

```[tasklist]
### [KubeArmor Client](https://clomonitor.io/projects/cncf/kubearmor#kubearmor-client)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing) (thanks @vishalrajofficial)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
```

```[tasklist]
### [Policy Templates](https://clomonitor.io/projects/cncf/kubearmor#policy-templates)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
- [ ] [Contributor License Agreement](https://clomonitor.io/docs/topics/checks/#contributor-license-agreement)
- [x] [Developer Certificate of Origin](https://clomonitor.io/docs/topics/checks/#developer-certificate-of-origin)
```

```[tasklist]
### [kvm-service](https://clomonitor.io/projects/cncf/kubearmor#kvm-service)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
- [x] [Recent release](https://clomonitor.io/docs/topics/checks/#recent-release)
```

```[tasklist]
### [kastore](https://clomonitor.io/projects/cncf/kubearmor#kastore)
- [x] [Contributing](https://clomonitor.io/docs/topics/checks/#contributing)
- [ ] [Maintainers](https://clomonitor.io/docs/topics/checks/#maintainers)
- [ ] [Contributor License Agreement](https://clomonitor.io/docs/topics/checks/#contributor-license-agreement)
- [x] [Developer Certificate of Origin](https://clomonitor.io/docs/topics/checks/#developer-certificate-of-origin)
```

### PR DESCRIPTION
**Pull request by vishalrajofficial**
**Purpose of PR?**:
This PR increases the clo-monitor score of kubeArmor.
Fixes #1353 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by vishalrajofficial** [comment]
I have submitted pull requests to the repositories of KubeArmor, policy-templates, and Kastore. In this regard, I humbly request your esteemed review of these contributions.

**Review by Ankurk99 — APPROVED** [review]
LGTM! Thanks for the PR

**Comment by vishalrajofficial** [comment]
@Ankurk99 Should I close this pull request? Another pull request relating to the same issue has already been merged.

**Comment by Ankurk99** [comment]
> Should I close this pull request? Another pull request relating to the same issue has already been merged.

@vishalrajofficial Yes, it has been addressed in the other PR. Thank you.

**Pull request closed without merging**
