### PR TITLE
Fix hyperlink in hardening guide

### PR DESCRIPTION
**Pull request by SD-13**
**Purpose of PR?**:

Fixes wrong hyperlink in [hardening guide doc](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/hardening_guide.md#what-is-the-source-of-these-hardening-policies).

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by SD-13** [comment]
@DelusionalOptimist PTAL. Thanks!

**Review by DelusionalOptimist — COMMENTED** [review]
LGTM. Thanks @SD-13!

**Review by DelusionalOptimist — APPROVED** [review]

**Comment by kranurag7** [comment]
@SD-13 can you please rebase this PR to main branch.

**Comment by SD-13** [comment]
@kranurag7 done!

**Review by kranurag7 — APPROVED** [review]
Thank you @SD-13

**Pull request merged**
