### PR TITLE
chore: Bump dependency versions

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Signed-off-by: Vyom-Yadav [jackhammervyom@gmail.com](mailto:jackhammervyom@gmail.com)

---

**Purpose of PR?**:

Bumps Dependency versions and go version in:

- `pkg/KubeArmorHostPolicy`
- `pkg/KubeArmorPolicy`

Bumps go version in CI tasks.

### CODE REVIEW

**Comment by daemon1024** [comment]
Thanks for looking into this.

But I don't think we need to update deps for the said pkgs. They are being deprecated in favour of `pkg/KubeArmorController`.

**Comment by Vyom-Yadav** [comment]
> Thanks for looking into this.
> 
> But I don't think we need to update deps for the said pkgs. They are being deprecated in favour of `pkg/KubeArmorController`.

These dependencies are referenced in `github.com/kubearmor/KubeArmor/tests` which is imported in `github.com/kubearmor/discovery-engine/tests`. So either the above-mentioned go modules should be made free from these dependencies or we need to update them.

These dependencies prohibit updating dependencies in other packages.

---

The primary problem is the usage of `github.com/kubearmor/KubeArmor/tests` in `github.com/kubearmor/discovery-engine/tests`.

**Comment by daemon1024** [comment]
> The primary problem is the usage of `github.com/kubearmor/KubeArmor/tests` in `github.com/kubearmor/discovery-engine/tests`.

Can we migrate deps in those (or create an issue for the same) to leverage `pkg/KubeArmorController` instead? It has all the methods that other 2 packages export.

**Comment by rksharma95** [comment]
we've already an open issue with PRs for it #1113 @Vyom-Yadav PTAL and we can close any one.

**Comment by Vyom-Yadav** [comment]
> we've already an open issue with PRs for it #1113 @Vyom-Yadav PTAL and we can close any one.

Since that one removes the dependency from `KubeArmorHostPolicy` and `KubeArmorPolicy` and updates the dependencies too, that one solves more problems.

Please bump dependencies in that PR to the latest compatible, that PR hasn't been updated in a while. You can close this one.

**Comment by DelusionalOptimist** [comment]
@rksharma95 @Vyom-Yadav is is possible to have this or PRs in #1113 merged before the upcoming v0.10 release this week?

FYI, @Aryan-sharma11 is also updating repo wide dependencies in #1218 before adding renovate bot. However in favor of the above, I think we can change that PR to not update the controllers. Thoughts?

**Comment by rksharma95** [comment]
@DelusionalOptimist yes definitely we can get PRs in #1113 merged asap. I will make it a priority for today.

**Review by DelusionalOptimist — APPROVED** [review]
LGTM! :rocket:

**Review by daemon1024 — APPROVED** [review]

**Pull request merged**
