### PR TITLE
License Headers

### PR DESCRIPTION
**Pull request by daemon1024**

### CODE REVIEW

**Comment by nam-jaehyun** [comment]
@daemon1024 can you also create a script to add the license headers if they do not exist?
there could be new files that someone creates. in this case, if we have a script, it would be nice to manage them I think.

**Comment by daemon1024** [comment]
Sure @nam-jaehyun.

**Comment by daemon1024** [comment]
I used https://github.com/google/addlicense to add the headers.
Should I commit the header file into some folder?

**Comment by nam-jaehyun** [comment]
> I used https://github.com/google/addlicense to add the headers.
> Should I commit the header file into some folder?

What do you mean committing the header file into some folder?

**Comment by daemon1024** [comment]
Like we have boilerplate in `pkg/KubeArmorPolicy/hack` Similarly the boilerplate header file for adding the headers via `addlicense`

**Comment by nam-jaehyun** [comment]
@daemon1024 can you add the header file and a script file that simply executes addlicense with full arguments in "contribution/license"?

**Pull request merged**
