### PR TITLE
fix(core, monitor, feeder): data races conditions

### LINKED ISSUE #842: Found Data Races in KubeArmor
## Bug Report

**General Information**

- Environment description - vagrant
- Kernel version (run `uname -a`) - Linux kubearmor-dev-next 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**

1. `go build -race -o kubearmor main.go` or modify the build target in Makefile to include `-race` flag
2. make run

**Expected behavior**

No data races found

**Actual Behaviour**

`Found 15 data race(s)` in my run. All of them seem to be in the beginning and when terminated.

image

### PR DESCRIPTION
**Pull request by rksharma95**
**Purpose of PR?**:
The changes proposed in this PR fixes #842 , Found 14 data races during my run and the changes handles all those conditions. No more data races found in subsequent trials/test with the proposed changes.
Fixes #842 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #842 
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Commit has unit tests

### CODE REVIEW

**Comment by rksharma95** [comment]
multicontainer ginkgo tests are passing locally on my system
```
Ran 4 of 4 Specs in 16.802 seconds
SUCCESS! -- 4 Passed | 0 Failed | 1 Flaked | 0 Pending | 0 Skipped
PASS
```

**Comment by DelusionalOptimist** [comment]
@rksharma95 can you please resolve the conflicts? : )

**Review by DelusionalOptimist — APPROVED** [review]
LGTM :+1: 
Failing gosec test irrelevant to the changes.

**Review by Shreyas220 — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
