### PR TITLE
chore(controller): deprecate kube-rbac-proxy with controller built-in auth protection

### LINKED ISSUE #1905: :warning: Action Required: Replace Deprecated gcr.io/kubebuilder/kube-rbac-proxy
## Description

:warning: **The image `gcr.io/kubebuilder/kube-rbac-proxy` is deprecated and will become unavailable.**
**You must move as soon as possible, sometime from early 2025, the GCR will go away.**

> _Unfortunately, we're unable to provide any guarantees regarding timelines or potential extensions at this time. Images provided under GRC will be unavailable from March 18, 2025, [as per announcement](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr). However, `gcr.io/kubebuilder/`may be unavailable before this date due [to efforts to deprecate infrastructure](https://github.com/kubernetes/k8s.io/issues/2647)._

- **If your project uses `gcr.io/kubebuilder/kube-rbac-proxy`, it will be affected.**
  Your project may fail to work if the image cannot be pulled. **You must take action as soon as possible.**

- However, if your project is **no longer using this image**, **no action is required**, and you can close this issue.

## Using the image `gcr.io/kubebuilder/kube-rbac-proxy`?

[kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) was historically used to protect the metrics endpoint. However, its usage has been discontinued in [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder). The default scaffold now leverages the [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization) feature provided by [Controller-Runtime](https://github.com/kubernetes-sigs/controller-runtime).

This feature provides integrated support for securing metrics endpoints by embedding authentication (`authn`) and authorization (`authz`) mechanisms directly into the controller manager's metrics server, replacing the need for (https://github.com/brancz/kube-rbac-proxy) to secure metrics endpoints.

### What To Do?

**You must replace the deprecated image `gcr.io/kubebuilder/kube-rbac-proxy` with an alternative approach. For example:**
- Update your project to use [`WithAuthenticationAndAuthorization`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/metrics/filters#WithAuthenticationAndAuthorization):
  > _You can fully upgrade your project to use the latest scaffolds provided by the tool or manually make the necessary changes. Refer to the [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907) for detailed instructions on how to manually update your project and test the changes._
- Alternatively, replace the image with another trusted source at your own risk, as its usage has been discontinued in Kubebuilder.

**For further information, suggestions, and guidance:**
- 📖 [FAQ and Discussion](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907)
- 💬 Join the Slack channel: [#kubebuilder](https://communityinviter.com/apps/kubernetes/community#kubebuilder).

> **NOTE:** _This issue was opened automatically as part of our efforts to identify projects that might be affected and to raise awareness about this change within the community. If your project is no longer using this image, **feel free to close this issue**._

We sincerely apologize for any inconvenience this may cause.

**Thank you for your cooperation and understanding!** :pray:

### PR DESCRIPTION
**Pull request by rksharma95**
**Purpose of PR?**:

Fixes #1905 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
with this PR `kube-rbac-proxy` would be deprecated therefore controller deployment will have a single container for kubearmor-controller manager only. operator should not deploy kube-rbac-proxy in any case. metric protection also disabled with this PR in effect as controller is not producing any metric at this point.

**Checklist:**
- [x] Bug fix. Fixes #1905 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by daemon1024 — DISMISSED** [review]

**Review by Aryan-sharma11 — COMMENTED** [review]
@rksharma95, why are we adding binary files `kubearmor-v1.x.x.tgz` , `kubearmor-operator-1.3.2.tgz` ?

**Comment by rootxrishabh** [comment]
@rksharma95 Please resolve conflicts

**Comment by rksharma95** [comment]
> @rksharma95, why are we adding binary files `kubearmor-v1.x.x.tgz` , `kubearmor-operator-1.3.2.tgz` ?

my bad! i added these by mistake, removed

**Review by rootxrishabh — DISMISSED** [review]
# LGTM!

## Environment
OS - Google Container - Optimized OS
Kernel - `6.1.112+`
Container Runtime - `containerd://1.7.23`
K8s env - `v1.30.6-gke.1125000`

## Kube-rbac not deployed (expected) && Enforcement confirmed on AppArmor
```yaml
rootxrishabh@Rishabhs-MacBook-Air KubeArmorOperator % k describe po kubearmor-controller-77bb969564-wkmjz -n kubearmor
Name:             kubearmor-controller-77bb969564-wkmjz
Namespace:        kubearmor
Priority:         0
Service Account:  kubearmor-controller
Node:             gke-rishab-cluster-ng-ae649047-dn25/10.128.0.25
Start Time:       Fri, 20 Dec 2024 11:46:54 +0530
Labels:           kubearmor-app=kubearmor-controller
                  pod-template-hash=77bb969564
Annotations:      container.apparmor.security.beta.kubernetes.io/manager: unconfined
                  kubearmor-policy: audited
Status:           Running
IP:               10.84.2.26
IPs:
  IP:           10.84.2.26
Controlled By:  ReplicaSet/kubearmor-controller-77bb969564
Containers:
  manager:
    Container ID:  containerd://bd9d3a035edaad07249a0782144b52c92c231d9fbdcc3d60155427f44a88fb71
    Image:         ttl.sh/kubearmor-controller-rbac:24h
    Image ID:      ttl.sh/kubearmor-controller-rbac@sha256:0bed0d14fd98d3f5040611f694605f34d153b18f32ae79645988e9677a3439fb
    Port:          9443/TCP
    Host Port:     0/TCP
    Command:
      /manager
    Args:
      --leader-elect
      --health-probe-bind-address=:8081
    State:          Running
      Started:      Fri, 20 Dec 2024 11:46:58 +0530
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        10m
      memory:     64Mi
    Liveness:     http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:    http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gvn7w (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubearmor-controller-webhook-server-cert
    Optional:    false
  kube-api-access-gvn7w:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubearmor.io/securityfs=yes
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             
rootxrishabh@Rishabhs-MacBook-Air templates % k exec -it nginx-bf5d5cf98-2tptx -- bash
root@nginx-bf5d5cf98-2tptx:/# apt
bash: /usr/bin/apt: Permission denied
root@nginx-bf5d5cf98-2tptx:/# exit
exit
command terminated with exit code 126
rootxrishabh@Rishabhs-MacBook-Air templates % k describe po nginx-bf5d5cf98-2tptx
Name:             nginx-bf5d5cf98-2tptx
Namespace:        default
Priority:         0
Service Account:  default
Node:             gke-rishab-cluster-ng-ae649047-dn25/10.128.0.25
Start Time:       Fri, 20 Dec 2024 11:47:49 +0530
Labels:           app=nginx
                  pod-template-hash=bf5d5cf98
Annotations:      container.apparmor.security.beta.kubernetes.io/nginx: localhost/kubearmor-default-nginx-nginx
                  kubearmor-policy: enabled
                  kubearmor-visibility: process,file,network,capabilities

**Review by daemon1024 — APPROVED** [review]

**Review by Aryan-sharma11 — APPROVED** [review]

**Pull request merged**
