### PR TITLE
docs(support-matrix): update Support Matrix for DOKS 

### LINKED ISSUE #1120: Support for DigitalOcean Kubernetes (DOKS)
## Feature Request

**Short Description**

Supporting [k8s cluster solution from Digital Ocean](https://www.digitalocean.com/products/kubernetes), aka DOKS.

**Describe the solution you'd like**

- [ ] Check if policy enforcement, observability, audit rules, network segmentation is supported
- [ ] Get output of `karmor probe`
- [ ] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)
- [ ] Provide and attach `karmor sysdump`

### PR DESCRIPTION
**Pull request by Amishakumari544**
**Purpose of PR?**:

Fixes #1120 
Update KubeArmor Support-matrix to have full support (both observability and enforcement) for DOKS
**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

### CODE REVIEW

**Comment by Amishakumari544** [comment]
Enforcement Supported: Yes
Audit/Observability supported: Yes
LSM Used: Apparmor


**karmor probe**

image

**Comment by Amishakumari544** [comment]
@Ankurk99 can you please review?

**Comment by Ankurk99** [comment]
Hey @Amishakumari544, thanks for the PR. 
Can you please send the `karmor sysdump` output generated file (file name will be karmor-sysdump-<time of creation>.zip) and the kernel configuration (`uname -a`)?

**Comment by Amishakumari544** [comment]
image

**Comment by Amishakumari544** [comment]
[karmor-sysdump-Tue Mar 21 14_59_12 IST 2023.zip](https://github.com/kubearmor/KubeArmor/files/11026847/karmor-sysdump-Tue.Mar.21.14_59_12.IST.2023.zip)

**Comment by Ankurk99** [comment]
Hey @Amishakumari544, I couldn't find any reference to DOKS in the sysdump you sent. Are you by any chance testing it on your local machine?

**Comment by Amishakumari544** [comment]
> Hey @Amishakumari544, I couldn't find any reference to DOKS in the system you sent. Are you by any chance testing it on your local machine?

yes, I was doing it locally, do I need to check somewhere else? I thought I have to follow the steps from [here](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md)

I am doing something wrong here?

**Comment by Ankurk99** [comment]
Ah! it's correct that you can follow the deployment guide but this issue is for testing KubeArmor on DigitalOcean Kubernetes Cluster. 
So you will need to first setup a k8s cluster on (DigitalOcean)[https://www.digitalocean.com/products/kubernetes] and then try KubeArmor on that.

**Comment by Amishakumari544** [comment]
> Ah! it's correct that you can follow the deployment guide but this issue is for testing KubeArmor on DigitalOcean Kubernetes Cluster. So you will need to first setup a k8s cluster on (DigitalOcean)[https://www.digitalocean.com/products/kubernetes] and then try KubeArmor on that.

Oh, my bad! I tried to sign in but it's asking for a card which I don't have. I only have a debit card  which its not accept.
image

**Comment by Ankurk99** [comment]
@nyrahul Can we get access to a DOKS cluster for testing this out?

**Comment by Ankurk99** [comment]
@Amishakumari544 sorry but we will need to close this issue, as we need to verify the work on DOKS env. 
Vyom volunteered to have an account on DigitalOcean and will be checking the support there.
Appreciate your efforts on the issue.

**Pull request closed without merging**
