### PR TITLE
forced the protocol to lowercase in AppArmorProfile

### LINKED ISSUE #1019: Network policies fails to apply (Apparmor)
## Bug Report

**General Information**

- lsm: AppArmor

**To Reproduce**

1. Apply this policy
``` yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: pol02
spec:
  action: Block
  network:
    matchProtocols:
    - protocol: TCP
  selector:
    matchLabels:
      app: dvwa-web
  severity: 1
```

**Expected behavior**

A block network policy should be applied

** Actual behavior**

The policy cannot be applied

image

**Proposed fix**

In apparmor profile generation, force the protocol to lower case.

### PR DESCRIPTION
**Pull request by kanhaiya04**
**Purpose of PR?**:

Fixes #1019 
Fixed the Network policy failure

**Does this PR introduce a breaking change?** No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** : Fixes #1019 

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by kanhaiya04** [comment]
Hey @achrefbensaad, I can't able to understand why 1 check got failed.
Is it not the right way to fix this?

**Comment by achrefbensaad** [comment]
Hi @kanhaiya04 , Thank you for your contribution.

Failures can occur due to a flaykiness of the CI.
On the other side, your current changes are CPU intensive. Please consider making the required changes in this block https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/enforcer/appArmorProfile.go#L223-L255

**Comment by kanhaiya04** [comment]
Hi @achrefbensaad, thanks for the guidance. I have made the changes accordingly, can you please review it.

**Comment by achrefbensaad** [comment]
Hi @kanhaiya04 , Thank you for your contribution.

**Review by daemon1024 — APPROVED** [review]
LGTM 👌🏽 Appreciate the contribution

**Comment by daemon1024** [comment]
`go-sec` should pass after we merge #1098

**Comment by achrefbensaad** [comment]
Hi @kanhaiya04 , Can you please rebase your code on top of main. Ill merge after a green pipeline.

**Comment by kanhaiya04** [comment]
Hi @achrefbensaad, Done.
Do I have to create PR again from main branch?

**Comment by achrefbensaad** [comment]
No, after rebasing, please push to this PR.

**Pull request merged**
