### PR TITLE
Add controller Health checks

### PR DESCRIPTION
**Pull request by s1ntaxe770r**
this PR addresses #764  and exposes a healthcheck endpoint for both controllers on port 8081 by default

### CODE REVIEW

**Comment by achrefbensaad** [comment]
Hey @s1ntaxe770r,
Can you please make the appropriate chanegs to the yaml files under `pkg/KubeArmorHostPolicy` , `pkg/KubeArmorPolicy` and `deployments/` to include liveness probes.
except that, the pr LGTM.

**Comment by s1ntaxe770r** [comment]
@achrefbensaad  re-review pls?

**Comment by achrefbensaad** [comment]
everything looks in place, except manifests under geeneric should be automatically generated.

- add the heath checks under objects.go 
- run make to generate a new manifest under generic folder.

**Comment by achrefbensaad** [comment]
@s1ntaxe770r can you please squash your commits?

**Comment by nam-jaehyun** [comment]
Let's wait until all comments are squashed to a single one.

**Comment by s1ntaxe770r** [comment]
🤔  @nam-jaehyun does this look good now?

**Pull request closed without merging**
