### PR TITLE
docs: Update the KubeArmor logo

### LINKED ISSUE #1147: change KubeArmor logo in Readme
KubeArmor is using the CamelCase notation in all places except for in the logo. The aim is to use a CamelCase notation in the logo as well and please find attached the logo to be used.

Task:
- [ ] replace the KubeArmor logo with the attached logo in the README
- [ ] check any places where CamelCase notation is not used and amend it.

kubearmor

### PR DESCRIPTION
**Pull request by Amishakumari544**
**Purpose of PR?**:

Fixes #1147 

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

### CODE REVIEW

**Comment by Chinwendu20** [comment]
Nice work

**Comment by nyrahul** [comment]
Thanks @Amishakumari544, few more changes required:
1. Looks like there is too much left/right spacing in the kubearmor logo image ... Attached is the updated image after removing the spaces.
2. The architecture diagram still has old casing .. attached is the updated arch diagram.

kubearmor
kubearmor

**Review by nyrahul — CHANGES_REQUESTED** [review]
Thanks @Amishakumari544, few more changes required:

Looks like there is too much left/right spacing in the kubearmor logo image ... Attached is the updated image after removing the spaces.
The architecture diagram still has old casing .. attached is the updated arch diagram.

**Comment by Amishakumari544** [comment]
I removed the unwanted space now @nyrahul can you check if its fine or not?

**Comment by nyrahul** [comment]
Hey @Amishakumari544 , the space needs to be removed from the png file. The logo file I attached in [the comment](https://github.com/kubearmor/KubeArmor/pull/1151#issuecomment-1465453039) has the edited png that has that space removed.

Secondly, the arch diagram png needs to updated in the readme page as well.

**Comment by nyrahul** [comment]
Hey @Amishakumari544 , The final changes look good to me. Please squash the commits into a single commit.

**Comment by Amishakumari544** [comment]
> Hey @Amishakumari544 , The final changes look good to me. Please squash the commits into a single commit.

apologise, for messing up. @nyrahul

**Review by nyrahul — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
