### PR TITLE
systemmonitor: parse relative paths

### LINKED ISSUE #299: Not able to get the full path, missing alerts
## Bug Report

**General Information**

- Environment description

Checked this issue from 'kubearmor-dev' (vagrant), but would happen in all environments

- Kernel version

4.15.0-151-generic

- Orchestration system version in use

Kubernetes version: 1.21.4

**To Reproduce**

Assume that KubeArmor is already running.

1. Apply wordpress-mysql

```
$ kubectl apply -f KubeArmor/examples/wordpress-mysql
```

2. Apply ksp-mysql-audit-dir.yaml

```
$ kubectl apply -f KubeArmor/examples/wordpress-mysql/security-policies/ksp-mysql-audit-dir.yaml
```

3. Get into the MySQL pod and run the following commands

```
$ kubectl -n wordpress-mysql exec -it [MySQL pod] -- bash

root@mysql-XXXX:/# ls /var/lib/mysql/
auto.cnf  ib_logfile0  ib_logfile1  ibdata1  mysql  performance_schema  wordpress

{"timestamp":1630059958,"updatedTime":"2021-08-27T10:25:58.346137Z","hostName":"kubearmor-dev","namespaceName":"wordpress-mysql","podName":"mysql-686cf4cc6f-r284p","containerID":"781283f67fa319f80c7eaea8a5ae0c618687141f5aeb8e5a22ab9c46c486d218","containerName":"mysql","hostPid":4484,"ppid":170,"pid":176,"uid":0,"policyName":"ksp-mysql-audit-dir","severity":"5","type":"MatchedPolicy","source":"/bin/ls /var/lib/mysql/","operation":"File","resource":"/var/lib/mysql/","data":"syscall=SYS_OPEN flags=O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC","action":"Audit","result":"Passed"}

root@mysql-XXXX:/# cd /var/lib/mysql/

< No Alert >

root@mysql-XXXX:/var/lib/mysql# ls
auto.cnf  ib_logfile0  ib_logfile1  ibdata1  mysql  performance_schema  wordpress

< No Alert >

root@mysql-XXXX:/var/lib/mysql# wc -l auto.cnf
2 auto.cnf

< No Alert >

root@mysql-XXXX:/var/lib/mysql# tail -n 1 /var/lib/mysql/auto.cnf 
server-uuid=9b5efc3c-0720-11ec-a155-5ac19625703c

{"timestamp":1630059989,"updatedTime":"2021-08-27T10:26:29.501726Z","hostName":"kubearmor-dev","namespaceName":"wordpress-mysql","podName":"mysql-686cf4cc6f-r284p","containerID":"781283f67fa319f80c7eaea8a5ae0c618687141f5aeb8e5a22ab9c46c486d218","containerName":"mysql","hostPid":4605,"ppid":170,"pid":179,"uid":0,"policyName":"ksp-mysql-audit-dir","severity":"5","type":"MatchedPolicy","source":"/usr/bin/tail -n 1 /var/lib/mysql/auto.cnf","operation":"File","resource":"/var/lib/mysql/auto.cnf","data":"syscall=SYS_OPEN flags=O_RDONLY","action":"Audit","result":"Passed"}
```

4. Apply ksp-wordpress-block-config.yaml

```
$ kubectl apply -f KubeArmor/examples/wordpress-mysql/security-policies/ksp-wordpress-block-config.yaml
```

5. Get into the WordPress pod and run the following commands

```
$ kubectl -n wordpress-mysql exec -it [WordPress pod] -- bash

root@wordpress-dbcd8b97b-pwfmc:/var/www/html# cat wp-config.php
cat: wp-config.php: Permission denied

< No Alert >

root@wordpress-dbcd8b97b-pwfmc:/var/www/html# cat /var/www/html/wp-config.php
cat: /var/www/html/wp-config.php: Permission denied

{"timestamp":1630060320,"updatedTime":"2021-08-27T10:32:00.130183Z","hostName":"kubearmor-dev","namespaceName":"wordpress-mysql","podName":"wordpress-dbcd8b97b-pwfmc","containerID":"c9cbf49c54a9f6723e4e4457b1617de74191c800502bb639d1d850bf4351770c","containerName":"wordpress","hostPid":5938,"ppid":198,"pid":204,"uid":0,"policyName":"ksp-wordpress-block-config","severity":"10","type":"MatchedPolicy","source":"/bin/cat /var/www/html/wp-config.php","operation":"File","resource":"/var/www/html/wp-config.php","data":"syscall=SYS_OPEN flags=O_RDONLY","action":"Block","result":"Permission denied"}
```

**Expected behavior**

In the case of the MySQL pod, any accesses in /var/lib/mysql should be audited, as defined in the ksp-mysql-audit-dir policy. However, when we run commands with relative paths, KubeArmor misses such commands, not generating alerts. On the other hand, when we run commands with absolute paths, KubeArmor detects them, generating alerts.

Similarly, KubeArmor should generate alerts against the access of '/var/www/html/wp-config.php' by '/bin/cat', as defined in the ksp-wordpress-block-config policy. However, KubeArmor does not generate alerts if the access occurs with relative paths while it generates alerts in the case of the access with the absolute path.

### PR DESCRIPTION
**Pull request by weirdwiz**
Fixes #299

### CODE REVIEW

**Comment by nam-jaehyun** [comment]
@weirdwiz It seems that we can now get the full path of files.
Then, do you think we can get the full path of an executable too?

**Comment by weirdwiz** [comment]
Not yet. To get full path for exec. We'll probably need to change the exec hook to a scheduler tracepoint.

**Comment by weirdwiz** [comment]
@nam-jaehyun can you revert this merge? there were still some tests failing, and the commits were not yet rebased and squashed
it would be good to go through a review process first.

**Comment by weirdwiz** [comment]
Thanks for reverting! Can you review the code? I'm currently working on fixing the tests

**Comment by weirdwiz** [comment]
Do you recommend opening another PR?

**Pull request merged**
