### PR TITLE
Replaced AccuKnox org images with KubeArmor

### LINKED ISSUE #1424: Replace AccuKnox org images with KubeArmor
On our contribution guide there are old images from the time when the KubeArmor was in AccuKnox org. We have to update those images to avoid confusion. 

https://github.com/kubearmor/KubeArmor/blob/main/contribution/contribution_guide.md

### PR DESCRIPTION
**Pull request by VamshiReddy02**
**Purpose of PR?**:

Fixes #1424
I Replaced all the AccuKnox org images with KubeArmor in [contribution_guide.md](https://github.com/kubearmor/KubeArmor/blob/main/contribution/contribution_guide.md). Please let me know if there are any changes to be made.

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by VamshiReddy02** [comment]
@ShubhamTatvamasi can you review this PR?

**Review by ShubhamTatvamasi — CHANGES_REQUESTED** [review]
We need all these images in white background.

**Comment by ShubhamTatvamasi** [comment]
Hi @VamshiReddy02, any update on the changes requested?

**Comment by VamshiReddy02** [comment]
Hey @ShubhamTatvamasi, sorry for the late reply just caught some work. I'm working on this PR. Just give me some time to update the changes which were requested.

**Comment by VamshiReddy02** [comment]
Hey @ShubhamTatvamasi, I updated the PR as requested. Please review it and let me know if any changes need to be made.

**Review by ShubhamTatvamasi — APPROVED** [review]

**Pull request merged**
