### PR TITLE
clean up KubeArmorAnnotation

### PR DESCRIPTION
**Pull request by nam-jaehyun**
- clean up KubeArmorAnnotation
- update GitHub Action

### CODE REVIEW

**Review by nyrahul — APPROVED** [review]
LGTM

**Comment by nyrahul** [comment]
@achrefbensaad , can you please review this code? (Not able to add you as reviewer!)

**Comment by achrefbensaad** [comment]
LGTM!
@nam-jaehyun I opened an PR https://github.com/kloudmax/KubeArmor/pull/1 to be merged before this gets to main, as while I was testing I noticied that `pod_mutation.go` does not honor the fallback logic as it uses `Fail` rather than `Ignore` (my bad).
I also regenerated the deployments yaml.

**Comment by achrefbensaad** [comment]
@nyrahul I cant be added as a reviewer as I do not have write access to the repository.

**Pull request merged**
