### PR TITLE
refactor(monitor) : add debug logs

### PR DESCRIPTION
**Pull request by daemon1024**
**Purpose of PR?**:

Ref #964 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Confirmed lost events after reducing the Page Size.

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by achrefbensaad — CHANGES_REQUESTED** [review]
LGTM, Can you please add exit messages here also https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/monitor/systemMonitor.go#L403-L422
and DCO is failing

**Comment by daemon1024** [comment]
> Can you please add exit messages here also https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/monitor/systemMonitor.go#L403-L422

didn't I already add? there's a single breaking point in the function. Added the log there already 🤔

**Comment by achrefbensaad** [comment]
> didn't I already add? there's a single breaking point in the function. Added the log there already 🤔

Sorry I miss read the line number.

**Review by achrefbensaad — APPROVED** [review]
LGTM

**Pull request merged**
