### PR TITLE
Update the Go version to 1.21

### PR DESCRIPTION
**Pull request by MeenuyD**
Update Go version to 1.21
#1613

### CODE REVIEW

**Review by Aryan-sharma11 — CHANGES_REQUESTED** [review]
The golang version in docker files needs to be updated as well.

**Review by DelusionalOptimist — CHANGES_REQUESTED** [review]
Please also update `go.mod` files in protobuf, deployments, KubeArmor and pkg/KubeArmorController and pkg/KubeArmorOperator.

**Comment by DelusionalOptimist** [comment]
@Aryan-sharma11 all tests are passing. Do we know why snyk failed? It says "Failed to process protobuf/go.mod ".
Will we need to update go version in snyk?

**Comment by Aryan-sharma11** [comment]
> @Aryan-sharma11 all tests are passing. Do we know why snyk failed? It says "Failed to process protobuf/go.mod ". Will we need to update go version in snyk?

I don't think we have the option to update go version in Snyk, @MeenuyD  are you updating the go version in go.mod using `go mod tidy` on a system with go 1.21 version or by updating the version in the go.mod files manually?

**Comment by Aryan-sharma11** [comment]
> > @Aryan-sharma11 all tests are passing. Do we know why snyk failed? It says "Failed to process protobuf/go.mod ". Will we need to update go version in snyk?
> 
> I don't think we have the option to update go version in Snyk, @MeenuyD are you updating the go version in go.mod using `go mod tidy` on a system with go 1.21 version or by updating the version in the go.mod files manually?

I think the go.mod built using 1.21 should look something like 
` go 1.21
toolchain go1.21.3`

**Comment by DelusionalOptimist** [comment]
> > > @Aryan-sharma11 all tests are passing. Do we know why snyk failed? It says "Failed to process protobuf/go.mod ". Will we need to update go version in snyk?
> > 
> > 
> > I don't think we have the option to update go version in Snyk, @MeenuyD are you updating the go version in go.mod using `go mod tidy` on a system with go 1.21 version or by updating the version in the go.mod files manually?
> 
> I think the go.mod built using 1.21 should look something like ` go 1.21 toolchain go1.21.3`

Is the toolchain directive mandatory? I think it only comes if go.mod has version `< 1.21`. For example, when I checkout this branch and execute `go mod tidy` with latest go (`1.22`) the toolchain directive doesn't get added for me. :thinking:

**Comment by MeenuyD** [comment]
I have change manually what command should i run

**Comment by DelusionalOptimist** [comment]
> I have change manually what command should i run

@Meenuyd Make sure you have go 1.21 or newer installed ([guide](https://go.dev/doc/install)) and then try running `go mod tidy` in all directories which have a `go.mod` file. If something changes, try committing that and pushing. If not, let us know.

**Comment by DelusionalOptimist** [comment]
@MeenuyD please rebase with the main branch. Some tests did not run because of merge conflicts.

**Comment by DelusionalOptimist** [comment]
Hey @MeenuyD any progress? Let us know if you need any help.

**Comment by MeenuyD** [comment]
Can you please review this pr #1642

**Pull request closed without merging**
