### PR TITLE
add annotation controller docs

### PR DESCRIPTION
**Pull request by achrefbensaad**
Signed-off-by: Achref Ben Saadd <achref9612@gmail.com>

### CODE REVIEW

**Comment by nyrahul** [comment]
Hey @achrefbensaad , is this still in draft phase? We can assume v0.5 as the release which will have annotation controller. Can we update the docs to reflect that and change it to normal PR?

**Comment by achrefbensaad** [comment]
@nyrahul Done.

**Review by nyrahul — APPROVED** [review]
LGTM

**Review by nyrahul — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
