### PR TITLE
fix(helm): quote configmap values

### LINKED ISSUE #1794: ConfigMap in KubeArmor helm chart is not properly quoted
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...):  k3s
- Kernel version (run `uname -a`): `Linux thunderbird 6.6.36-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 27 Jun 2024 12:26:27 +0000 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6+k3s1
```
- Helm Version: `version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"}`
- Link to relevant artifacts (policies, deployments scripts, ...): NA
- Target containers/pods: NA

**To Reproduce**

1. Setup a k8s cluster
2. Run the command: `helm upgrade --install kubearmor kubearmor/kubearmor -n kubearmor --create-namespace`
3. Error occurs
```
Release "kubearmor" does not exist. Installing it now.
Error: 1 error occurred:
        * ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal bool into Go struct field ConfigMap.data of type string
```

**Expected behavior**

KubeArmor Helm chart is deployed without any error
```
Release "kubearmor" does not exist. Installing it now.
NAME: kubearmor
LAST DEPLOYED: Wed Jul  3 13:09:24 2024
NAMESPACE: kubearmor
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Why is this happening?**
ConfigMaps are supposed to handle map[string]string. In a recent [merge](https://github.com/kubearmor/KubeArmor/commit/86cf299d98347c3295f725d54659fbf49d8fa90a#diff-718e58bd527467eebbabb47ec0737699857d3a3e540d11787bc95927cdc8764b), more field were added such as alertThrottling, maxAlertPerSec, throttleSec. The value for these fields are not string but boolean and ints. Hence the ConfigMap cannot be parsed

### PR DESCRIPTION
**Pull request by tesla59**
**Purpose of PR?**:

Fixes https://github.com/kubearmor/KubeArmor/issues/1794

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Tested using `helm upgrade --install kubearmor ./deployments/helm/KubeArmor -n kubearmor --create-namespace`

**Additional information for reviewer?** :
No

**Checklist:**
- [x] Bug fix. Fixes #1794 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by tesla59** [comment]
api documentation verifies the field in the data section is map[string]string 
https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/config-map-v1/

**Comment by tesla59** [comment]
Hey @daemon1024 can u please review this

**Review by Prateeknandle — APPROVED** [review]
LGTM 👍🏼 

@tesla59 thanks for reporting the issue and also handling it.

**Review by rksharma95 — APPROVED** [review]
LGTM :+1:

**Comment by Aryan-sharma11** [comment]
@tesla59  can you rebase the branch as we have fixed the CI recently

**Comment by tesla59** [comment]
@Aryan-sharma11 done

**Review by kranurag7 — APPROVED** [review]
LGTM, thanks @tesla59

**Pull request merged**
