### PR TITLE
docs: Correct match label in Host policies

### PR DESCRIPTION
**Pull request by SD-13**
**Purpose of PR?**:

This PR updates incorrect match labels in host policies

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by SD-13** [comment]
@daemon1024 PTAL when you get time. Thanks!!

**Comment by navin772** [comment]
@SD-13 we can use `kubernetes.io/hostname` when KubeArmor is running in `k8s` mode to secure the host/nodes. See [kubernetes.io/hostname](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname).
`kubearmor.io/hostname` works for `non_k8s` mode (systemd and docker).

**Comment by daemon1024** [comment]
@SD-13 Thanks for the PR, but as @navin772 said this is not needed in kubernetes mode. 
I don't this PR is needed. 
Are you facing issues with HSPs?

**Comment by SD-13** [comment]
@daemon1024 True. I created this PR after trying hsp in non-k8s env and changed the doc from that POV. @navin772 Thanks for correcting me!
I am closing this PR...

**Comment by DelusionalOptimist** [comment]
@SD-13 @daemon1024 
IMO it would still be useful if we could highlight this difference in the documentation somehow. It is easy to miss.
Maybe we could have this in the policy examples page, the getting started guide for VMs or in the FAQ. Thoughts?

**Pull request closed without merging**
