### PR TITLE
Minikube Cluster Setup Documentation

### PR DESCRIPTION
**Pull request by sayantani11**
This PR address #496 

@daemon1024 @nyrahul 
These issues: #492 #493 #494 #495 can also be addressed in this PR, I guess makes thing easier.

### CODE REVIEW

**Comment by daemon1024** [comment]
@sayantani11 as I mentioned in https://github.com/kubearmor/KubeArmor/pull/569#issuecomment-1027573907

We want to use collapsible sections in our deployment guide, instead of referencing to external documentation. Can you handle that change?

> These issues: https://github.com/kubearmor/KubeArmor/issues/492 https://github.com/kubearmor/KubeArmor/issues/493 https://github.com/kubearmor/KubeArmor/issues/494 https://github.com/kubearmor/KubeArmor/issues/495 can also be addressed in this PR, I guess makes thing easier.

Sure if you want to, I segregated them into separate issues so as to make it easier to track..

**Comment by sayantani11** [comment]
@daemon1024 Yes I can!! Cool I'll do it

**Comment by sayantani11** [comment]
> @sayantani11 as I mentioned in [#569 (comment)](https://github.com/kubearmor/KubeArmor/pull/569#issuecomment-1027573907)
> 
> We want to use collapsible sections in our deployment guide, instead of referencing to external documentation. Can you handle that change?
> 
> > These issues: #492 #493 #494 #495 can also be addressed in this PR, I guess makes thing easier.
> 
> Sure if you want to, I segregated them into separate issues so as to make it easier to track..

But I wanted to see an example of how the things should turn out to be.

**Comment by daemon1024** [comment]
So we have #Prerequisites section in our deployment guide!
We can repurpose it for this.

Something in the lines of

## Prerequisites / Kubernetes Cluster Setup
*	<details>
 	<summary><b>EKS</b></summary> 
  		# EKS STuff
	</details>
*	<details>
 	<summary>Minikube</summary> 
  		#  STuff
	</details>
*	<details>
 	<summary>k3s</summary> 
  		#  STuff
	</details>
	
<details>
	<summary>Code for the same</summary>
	
	```
	  ## Prerequisites / Kubernetes Cluster Setup
	  *	<details>
	 	  <summary><b>EKS</b></summary> 
	  		  # EKS STuff
		  </details>
	  *	<details>
	 	  <summary>Minikube</summary> 
	  		  #  STuff
		  </details>
	  *	<details>
	 	  <summary>k3s</summary> 
	  		  #  STuff
		  </details>
	```
</details>
	
Lemme know if you think there might be a better way to handle this

**Comment by sayantani11** [comment]
@daemon1024 Got it!!

**Comment by daemon1024** [comment]
Hey @sayantani11 👋🏽 , Any updates on this?

**Pull request closed without merging**
