### PR TITLE
fix(monitor): Added handling when casting a type in SystemMonitor fails

### PR DESCRIPTION
**Pull request by haytok**
If KubeArmor is running in systemd mode, the following error may occur.

  ```
  Oct 13 05:10:25 ip-172-31-47-253 kubearmor[54156]: panic: interface conversion: interface {} is string, not []string
  Oct 13 05:10:25 ip-172-31-47-253 kubearmor[54156]: goroutine 43 [running]:
  Oct 13 05:10:25 ip-172-31-47-253 kubearmor[54156]: github.com/kubearmor/KubeArmor/KubeArmor/monitor.(*SystemMonitor).TraceSyscall(0xc0000fe600)
  Oct 13 05:10:25 ip-172-31-47-253 kubearmor[54156]:         /home/ubuntu/KubeArmor/KubeArmor/monitor/systemMonitor.go:691 +0x1a25
  Oct 13 05:10:25 ip-172-31-47-253 kubearmor[54156]: created by github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).MonitorSystemEvents in goroutine 16
  Oct 13 05:10:25 ip-172-31-47-253 kubearmor[54156]:         /home/ubuntu/KubeArmor/KubeArmor/core/kubeArmor.go:245 +0xcc
  Oct 13 05:10:27 ip-172-31-47-253 systemd[1]: kubearmor.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
  Oct 13 05:10:27 ip-172-31-47-253 systemd[1]: kubearmor.service: Failed with result 'exit-code'.
  ```

This is because a panic occurred when casting an object with interface{} to an object of type []string failed. When casting types, handling when casting fails is necessary.

Therefore, in this fix, we will add handling when casting fails, and fix it so that panic does not occur even if type casting fails.

**Purpose of PR?**:

No

**Does this PR introduce a breaking change?**

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

Handling when casting fails has been added to the implementation below.

- https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/monitor/systemMonitor.go#L691

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

N/A

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by haytok** [comment]
Hi, @daemon1024 
Could you review this when you have time ?
If you don't need it, you can close it .

**Review by daemon1024 — APPROVED** [review]
Looks Good to me. We should avoid direct type conversions wherever needed.
Thanks for handling it. Can you rebase the PR to fix the CI?

**Review by DelusionalOptimist — COMMENTED** [review]
@haytok Thank you for this fix! Just a small comment.

I think we can also avoid doing the same assertion again a few lines below:
https://github.com/kubearmor/KubeArmor/blob/3deb7a199d95b61a657b257244637bcf62309c17/KubeArmor/monitor/systemMonitor.go#L707-L719

Further, this processing seems similar to the one we already have in `BuildPidNode`, so I think we can use the returned value here instead of going through the args again. WDYT @daemon1024?
https://github.com/kubearmor/KubeArmor/blob/3deb7a199d95b61a657b257244637bcf62309c17/KubeArmor/monitor/processTree.go#L137-L145

**Comment by haytok** [comment]
Thanks for comments !!!

@daemon1024 

>  Thanks for handling it. Can you rebase the PR to fix the CI?

Sure, I'll update the main branch on fork repository and rebase this branch. 

@DelusionalOptimist 

> I think we can also avoid doing the same assertion again a few lines below:
> Further, this processing seems similar to the one we already have in BuildPidNode, so I think we can use the returned value here instead of going through the args again. WDYT @daemon1024?

If change the code based on DelusionalOptimist's advice, I think it will look like this. Is it right? 

```bash
haytok KubeArmor [added-handling-when-casting-a-type-in-SystemMonitor-fails]
> git status
On branch added-handling-when-casting-a-type-in-SystemMonitor-fails
Your branch and 'origin/added-handling-when-casting-a-type-in-SystemMonitor-fails' have diverged,
and have 19 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   KubeArmor/monitor/systemMonitor.go

no changes added to commit (use "git add" and/or "git commit -a")
haytok KubeArmor [added-handling-when-casting-a-type-in-SystemMonitor-fails]
> git diff KubeArmor/monitor/systemMonitor.go
diff --git a/KubeArmor/monitor/systemMonitor.go b/KubeArmor/monitor/systemMonitor.go
index 002a569b43c4..4ed945fd73dd 100644
--- a/KubeArmor/monitor/systemMonitor.go
+++ b/KubeArmor/monitor/systemMonitor.go
@@ -687,8 +687,18 @@ func (mon *SystemMonitor) TraceSyscall() {

                        } else if ctx.EventID == SysExecve {
                                if len(args) == 2 { // enter
+                                       var execPath string
+                                       var nodeArgs []string
+
+                                       if val, ok := args[0].(string); ok {
+                                               execPath = val
+                                       }
+                                       if val, ok := args[1].([]string); ok {
+                                               nodeArgs = val
+                                       }
+
                                        // build a pid node
-                                       pidNode := mon.BuildPidNode(containerID, ctx, args[0].(string), args[1].([]string))
+                                       pidNode := mon.BuildPidNode(containerID, ctx, execPath, nodeArgs)
                                        mon.AddActivePid(containerID, pidNode)

                                        // if Policy is not set
@@ -705,17 +715,9 @@ func (mon *SystemMonitor) TraceSyscall() {
                                        log := mon.BuildLogBase(ctx.EventID, ContextCombined{ContainerID: containerID, ContextSys: ctx})

                                        // add arguments
-                                       if val, ok := args[0].(string); ok {
-                                               log.Resource = val // procExecPath
-                                       }
-                                       if val, ok := args[1].([]string); ok {
-                                               for idx, arg := range val { // procArgs
-                                                       if idx == 0 {
-                                                               continue
-                                                       } else {
-                                                               log.Resource = log.Resource + " " + arg
-                                                       }
-                                               }
+                                       log.Resource = execPath
+                                       if pidNode.Args != "" {
+                                               log.Resource = log.Resource + " " + pidNode.Args
                                        }

                                        log.Operation = "Process"
```

**Comment by daemon1024** [comment]
Yup the changes LGTM.

Thanks @DelusionalOptimist for the suggestion.

Let's handle them @haytok

**Comment by haytok** [comment]
@daemon1024 

Thanks for comments !!! I have updated !

**Review by DelusionalOptimist — APPROVED** [review]
LGTM. Thank you @haytok! :rocket:

**Comment by haytok** [comment]
Thanks for merged !!!

**Pull request merged**
