### PR TITLE
Minikube Cluster Setup Documentation

### PR DESCRIPTION
**Pull request by sayantani11**
This PR solves #496 
I guess we can add other environment setup documentation to this section.

### CODE REVIEW

**Comment by nyrahul** [comment]
@sayantani11, You need to rebase your branch against current main to remove that go-sec error in CI.

**Comment by sayantani11** [comment]
> @sayantani11, You need to rebase your branch against current main to remove that go-sec error in CI.

But it's rebased, there isn't any error from my side as much as I can see. Looking into it!

**Comment by daemon1024** [comment]
Hey @sayantani11 thanks for the PR.

As mentioned in the meta issue https://github.com/kubearmor/KubeArmor/issues/477

We wanted to use collapsible sections to include docs as part of single file to avoid redirecting users to various links. Can you update your PR to accomodate that?

More about collapsible sections https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

**Comment by nam-jaehyun** [comment]
the go-sec issue was fixed in recent commits.
@sayantani11 If you rebase the branch again, the issue will disappear in the GitHub action as well.

**Pull request closed without merging**
