### PR TITLE
support matrix update for ubuntu 16.04

### LINKED ISSUE #1041: check support for ubuntu 16.04
There has been a request from a user to check whether kubearmor supports ubuntu 16.04.

Tasks:
- [ ] Create a k8s cluster using Ubuntu 16.04 (either using kubeadm or using k3s)
- [ ] Is enforcement supported? What is the LSM used?
- [ ] Is observability supported? Depends on whether eBPF is supported by the kernel
- [ ] Get output of `karmor probe`
- [ ] Update [kubearmor support matrix](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/support_matrix.md)

### PR DESCRIPTION
**Pull request by VedRatan**
Signed-off-by: Ved Ratan <vedratan8@gmail.com>

**Purpose of PR?**:

Fixes #1041

**Below are the screenshots to verify working of kubearmor on ubuntu 16.04**

Screenshot 2023-01-26 134142
 
**Below is the output of the command as mentioned by @nyrahul**

image

image

**Checklist:**
- [x] Bug fix. Fixes #1041 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by Ankurk99** [comment]
Hey @VedRatan, Can you please share the content of the generated folder "Ubuntu 16.04.7 LTS" instead of the ss? We want to check their output.
Also as disucussed earlier https://github.com/kubearmor/KubeArmor/issues/1041#issuecomment-1404694171, can you also check visibility?

**Comment by VedRatan** [comment]
oh sure @Ankurk99, will share it in a while

**Comment by VedRatan** [comment]
[Ubuntu16.04.zip](https://github.com/kubearmor/KubeArmor/files/10511773/Ubuntu16.04.zip)
@Ankurk99 @nyrahul I've attached the .zip file of the folder ubuntu 16.04.7 LTS

**Comment by nyrahul** [comment]
@Ankurk99 , turns out Ubuntu 16.04.7 uses kernel version 4.15 that has support for eBPF ([ref, expand on BPF/eBPF section](https://github.com/nyrahul/linux-kernel-configs#bpfebpf-support)).

**Comment by Ankurk99** [comment]
Okay, then I think we are good to go!

**Review by nyrahul — APPROVED** [review]

**Review by Ankurk99 — APPROVED** [review]

**Pull request merged**
