### PR TITLE
Added CI job to compile KubeArmor

### PR DESCRIPTION
**Pull request by zeborg**
### Related issue
#616 
### Proposed changes
* Added CI job to compile KubeArmor at every push or PR against `main` branch
* Fixed an error while installing KubeArmor dependencies within workflow container by defining `LLVM_ROOT` env var before bcc cmake

### CODE REVIEW

**Comment by zeborg** [comment]
cc - @h3llix @nyrahul

**Comment by nyrahul** [comment]
@zeborg, I don't see any code in the yaml that builds the code at "every commit" level ! CC: @Ankurk99

**Comment by zeborg** [comment]
@nyrahul I guess I might not have understood the issue properly!

Can you please elaborate what a "commit" refers to here? I thought it meant every push / PR made against `main`.

**Comment by nyrahul** [comment]
> @nyrahul I guess I might not have understood the issue properly!
> 
> Can you please elaborate what a "commit" refers to here? I thought it meant every push / PR made against `main`.

A PR could be made up of multiple commits. We expect every commit to be self-sufficient i.e., solves a problem and is compilable/testable/revertable. We want the ability to check/ensure that every commit within a PR is compilable (and later testable). This way if needed we can revert individual commits. Further we want the ability to handle git-bisect to figure out which commit might have broken the tests.

Thus the requirement is that if a PR contains multiple commits, the `make` has to be done at every individual commit level.

@Ankurk99 had handled the same for cilium repo in [this PR](https://github.com/cilium/cilium/pull/15659) (for ref). (We already have PR-level make and tests for Kubearmor)

**Comment by zeborg** [comment]
Oh ok, I understand it now, thanks!
I kinda had this similar thought earlier as well, but I believe to tackle with this issue the user could just squash the commits in their PR, which is what we're doing in the `kubernetes-sigs/cluster-api-provider-aws` repo as well by making it a necessary procedure for every PR.

**Comment by nyrahul** [comment]
Closing the PR for inactivity. The draft code does not handle the requirement.

**Pull request closed without merging**
