### PR TITLE
adds controller healthchecks

### LINKED ISSUE #764: Add health check endpoints for hostpolicy and policy controllers
## Feature Request

**Short Description**

hostpolicy and policy controllers should expose a health check endpoint.

**Is your feature request related to a problem? Please describe the use case.**

fixes point 13 in https://github.com/kubearmor/KubeArmor/issues/733

### PR DESCRIPTION
**Pull request by s1ntaxe770r**
Signed-off-by: Jubril Oyetunji <jubril@accuknox.com>

### CODE REVIEW

**Comment by s1ntaxe770r** [comment]
@nam-jaehyun  messed up the previous branch this should be much cleaner 😅

**Comment by s1ntaxe770r** [comment]
@achrefbensaad review pls?

**Review by achrefbensaad — APPROVED** [review]
LGTM

**Comment by s1ntaxe770r** [comment]
@achrefbensaad  shall I merge?

**Comment by achrefbensaad** [comment]
yes go ahead @s1ntaxe770r

**Comment by s1ntaxe770r** [comment]
oh wait I can't , @achrefbensaad 
image

**Comment by achrefbensaad** [comment]
No problem, Merging ...

**Pull request merged**
