### PR TITLE
update the way to map containerIDs and PidNS/MntNS

### PR DESCRIPTION
**Pull request by nam-jaehyun**
- update the way to map containers to PID/MNT namespaces
  (related to #193)
- update test scripts

### CODE REVIEW

**Comment by oneiro-naut** [comment]
@nam-jaehyun The mnt_id we get in ebpf code(system_monitor.c) does not match with any actual mnt_id we get using readlink command. And so we are not getting any container log. Because this lookup returns empty containerID(because key used does not match with keys already present):https://github.com/kubearmor/KubeArmor/blob/155b35d3bfb0c8057b3aa102bf8f6d7a0cb42530/KubeArmor/monitor/systemMonitor.go#L454
And so all of them are skipped here:
https://github.com/kubearmor/KubeArmor/blob/155b35d3bfb0c8057b3aa102bf8f6d7a0cb42530/KubeArmor/monitor/systemMonitor.go#L467

**Comment by nam-jaehyun** [comment]
@oneiro-naut could you show me some screenshots for better understanding?

**Comment by oneiro-naut** [comment]
@nam-jaehyun I just compared these 2 MntID and they seem to be different for same containerID.
[1]https://github.com/kubearmor/KubeArmor/blob/155b35d3bfb0c8057b3aa102bf8f6d7a0cb42530/KubeArmor/monitor/systemMonitor.go#L454
and
[2]https://github.com/kubearmor/KubeArmor/blob/155b35d3bfb0c8057b3aa102bf8f6d7a0cb42530/KubeArmor/core/dockerHandler.go#L233

**Comment by oneiro-naut** [comment]
@nam-jaehyun I found the cause. We need to incorporate [this]( https://github.com/iovisor/bcc/pull/3540) change in mnt_namespace struct defintion based on kernel versions. I tested it and now its working.

**Comment by nam-jaehyun** [comment]
@oneiro-naut could you make a PR for this change?

**Comment by oneiro-naut** [comment]
> @oneiro-naut could you make a PR for this change?

Sure thing.

**Pull request merged**
