### PR TITLE
feat(security): Refine hostPaths/capabilities in deployments and remove init container

### PR DESCRIPTION
**Pull request by daemon1024**
**Purpose of PR?**:

KubeArmor Init container is responsible for compiling our eBPF System Monitor. The compilation needs to happen on client machine because of kernel dependencies.

But with BPF CORE, we don't need it. But BTF info is only available on kernel above 5.2.

This PR ships a CORE compiled object file in main kubearmor image. And let's operator decide if init container needs to be deployed or not based on availability of BTF info.

**Does this PR introduce a breaking change?**

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

Deployed on both btf/non btf environments

**Additional information for reviewer?** :
Documentation for the hostpaths used by kubearmor :-
https://github.com/kubearmor/KubeArmor/wiki/HostPath-Mounts-Used-by-KubeArmor-%F0%9F%9A%A7%5BWIP%5D

Future steps would include adding an option to provide custom btf file such that users do not need to deploy init image on older kernels as well, provided they can make BTF info available. 
**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

<!--

The PR title message must follow convention:
`<type>(<scope>): <subject>`.

Where: <br />
- `type` is to define what type of PR is this.
  Most common types are:
    - `feat`      - for new features, not a new feature for build script
    - `fix`       - for bug fixes or improvements, not a fix for build script
    - `chore`     - changes not related to production code
    - `docs`      - changes related to documentation
    - `style`     - formatting, missing semi colons, linting fix etc; no significant production code changes
    - `test`      - adding missing tests, refactoring tests; no production code change
    - `refactor`  - refactoring production code, eg. renaming a variable or function name, there should not be any significant production code changes

- `scope` is a single word that best describes where the changes fit.
    - feature(`monitor`,`enforcer`)
    - test(`tests`, `bdd`)
    - chore(`build`)
- `subject` is a single line brief description of the changes made in the pull request.

### CODE REVIEW

**Comment by daemon1024** [comment]
Let's test it out on kernel version 4.18 with initDeploy=false.

**Comment by DelusionalOptimist** [comment]
- Add final BPF LSM manifest with volume mounts for references
-

**Comment by Aryan-sharma11** [comment]
[apparmor-manifest.txt](https://github.com/kubearmor/KubeArmor/files/15464890/apparmor-manifest.txt)
[bpflsm-kubearmor-manifest.txt](https://github.com/kubearmor/KubeArmor/files/15465629/bpflsm-kubearmor-manifest.txt)

**Review by daemon1024 — COMMENTED** [review]
LGTM 👌🏽

**Review by rksharma95 — DISMISSED** [review]
tested locally on host with kernel version `6.6.10-76060610-generic` 
LGTM :rocket:

**Review by Prateeknandle — DISMISSED** [review]
LGTM 👍🏼

**Review by rksharma95 — DISMISSED** [review]

**Review by DelusionalOptimist — DISMISSED** [review]
LGTM. Great work @Aryan-sharma11! 

Need opinions on whether we need to expose `initDeploy` through configuration (Helm/KAConfig)?
cc @daemon1024 @rksharma95

**Review by DelusionalOptimist — APPROVED** [review]
LGTM!

**Review by rksharma95 — APPROVED** [review]

**Pull request merged**
